# Generated by Django 3.2.8 on 2021-12-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
