# Generated by Django 3.2.8 on 2021-12-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='is_superuser',
        ),
    ]
