# Generated by Django 3.2.8 on 2021-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_faculty',
            field=models.BooleanField(default=True),
        ),
    ]
